DiseasePredictor/DiseasePredictor/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from MainApp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home_page),
    url('^Doctor/', include('Doctor.urls', namespace = 'Doctor')),
    url('^Diseases/', include('Diseases.urls', namespace = 'Diseases')),
    url('^Main/', include('MainApp.urls', namespace = 'MainApp')),
]

from . import settings
from django.contrib.staticfiles.urls import static
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DiseasePredictor/Diseases/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = "Diseases"

urlpatterns = [
        path("input/", views.input_view, name="Input"),
        ]

DiseasePredictor/Doctor/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'Doctor'

urlpatterns = [
        url('^register/$', views.register , name="Registration"),
        url('^login/$', views.login_user , name="Login"),
        url('^logout/$', views.logout_user , name="Logout"),
        url('^adder/$', views.add_disease , name="Adder"),
        ]

DiseasePredictor/MainApp/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'MainApp'

urlpatterns = [
        url('^about/$', views.about_page , name="About")
        ]

DiseasePredictor/media/templates/about.html
<!DOCTYPE html>
<html>
   <head>
      <title>About</title>
      <style>
            body{
            background-color: #1164b4;
            }
          .div1{
          background-color:white;
          margin: 20px;
          margin-right: 5px;
          margin-top: 50px ;
          border-radius: 25px;
          padding: 30px;
          text-align: center;
          font-size:20px;
          box-shadow: 0px 5px 20px rgba(0,0,0,0.5);
          font-family: 'Ubuntu', sans-serif;
          }    
      ul.about{
      	align : left;
	text-align : left;
      }
      </style>
   </head>
   <body>
	   {% include "menu-template.html" %}
      <div class="div1">
            <h1>About</h1>
            <br>
            <p align="left">Hi,Welcome to Prognosist!</p>
            <p align="left">Prognosis is a web application that uses machine learning algorithms to identify patterns in the dataset and predict a disease. Users can input symptoms and the system predicts accurately.
                We have also tried to improve the dataset by allowing doctors to add data to the dataset. Our system can mainly be used if the doctors are unable to predict a disease. We believe that our application
                can help in significantly improving the accuracy and speed of diagnosis.  </p>
            <p align="left"> Currently the application is in <b>beta</b> stage. In the upcoming updates we will try to improve analysis to try and predict if there is an outbreak. With a lot of input from doctors, we believe
                our application can easily detect an increase in certain symptoms and prevent an outbreak like another COVID. </p>
            <p align="left"><b>Developed by:</b></p>
            <ul class="about"  align="left">
                <li>Pratik Garai</li>
                <li>Jerry George Jaimon</li>
                <li>Shubh Prachauri</li>
                <li>Surya.S</li>
            </ul>
            <p align="left"><b>Dataset used:</b> &nbsp
            <a href="https://www.kaggle.com/rabisingh/symptom-checker">https://www.kaggle.com/rabisingh/symptom-checker</a>
            </p>
            <p align="left"><b>Image used:</b> &nbsp
	    <a href="https://www.freepik.com/free-photos-vectors/medical">Medical photo created by freepik - www.freepik.com</a>
            </p>
	    <p align="left"><b>Libraries/Frameworks Used:</b></p>
            <ul class="about"  align="left">
                <li>Django (Python)</li>
                <li>Sklearn (Python)</li>
                <li>Argon2 (Python)</li>
                <li>Requests (Python)</li>
                <li>Json (Python)</li>
                <li>Pickle (Python)</li>
                <li>jQuery (JavaScript)</li>
            </ul>
        </div>
   </body>
</html>

DiseasePredictor/media/templates/data_adder.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Doctor's records</title>
    <style>
          body{
		  background-color: #1164b4;
          }
         .div1{
         background-color:white;
         margin: 20px;
         margin-top: 50px ;
         border-radius: 25px;
         padding: 10px;
         text-align: center;
         box-shadow: 0px 5px 20px rgba(0,0,0,0.5);
         font-family: 'Ubuntu',sans-serif;
         }
        .switch {
          position: relative;
          display: inline-block;
          width: 35px;
          height: 24px;
        }
        /* Hide default HTML checkbox */
        .switch input {
          opacity: 0;
          width: 0;
          height: 0;
        }
        /* The slider */
        .slider {
          position: absolute;
          cursor: pointer;
          top: 0;
          left: 0;
          right: 0;
          bottom: 0;
          background-color: #ccc;
          -webkit-transition: .4s;
          transition: .4s;
        }
        .slider:before {
          position: absolute;
          content: "";
          height: 15px;
          width: 15px;
          left: 4px;
          bottom: 4px;
          background-color: white;
          -webkit-transition: .4s;
          transition: .4s;
        }
        input:checked + .slider {
          background-color: #2196F3;
        }
        input:focus + .slider {
          box-shadow: 0 0 1px #2196F3;
        }
        input:checked + .slider:before {
          -webkit-transform: translateX(13px);
          -ms-transform: translateX(13px);
          transform: translateX(13px);
        }
        /* Rounded sliders */
        .slider.round {
          border-radius: 10px;
        }
        .slider.round:before {
          border-radius: 50%;
        }
        .column {
        display : inline-block;
        }
        
    </style>
</head>
<body>
	{% include "menu-template.html" %}
    <div class="div1">
            <h1>Form</h1>
            <h3 align="left">&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
                &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
                &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
                Fill up the form and submit it:</h3>
	    <form method="POST">
		    {% csrf_token %}
        <p><b>Age: &nbsp &nbsp <input type="number"/></b></p>
            <div align="center">
            <p style="font-size:20px;"><b>Symptoms</b></p>
                <div class="column" align="left">
                    {% for i in list_1%}
                    <p> {{i}}
                    <label class="switch">
                      <input id='{{i}}' type="checkbox">
                      <span class="slider round"></span>
                    </label>
                    </p>
                    {% endfor %}
                </div>
                <div class="column" align="left">
                    {% for i in  list_2%}
                    <p> {{i}}
                    <label class="switch">
                      <input id='{{i}}' type="checkbox">
                      <span class="slider round"></span>
                    </label>
                    </p>
                    {% endfor %}
                </div>
                <div class="column" align="left">
                    {% for i in list_3%}
                    <p> {{i}}
                    <label class="switch">
                      <input id='{{i}}' type="checkbox">
                      <span class="slider round"></span>
                    </label>
                    </p>
                    {% endfor %}
                </div>
                </div>
            <p><b>Diagnosis :
                <input text="text" id="Diagnosis" required></b></p>
        <input type="submit" class="button1" value="Submit">
        </form>    </div></body>
</html>

DiseasePredictor/media/templates/home.html
<!DOCTYPE html>
<html>
   <head>
      <title>About</title>
      <style>
          body{
             background: url("https://image.freepik.com/free-photo/young-handsome-physician-medical-robe-with-stethoscope_1303-17818.jpg") ;
             background-repeat: no-repeat;
             background-size: cover;
	  }
	  .nav{
	background-color:white;
	margin: 20px;
	margin-top: 50px ;
	border-radius: 25px;
	padding: 10px;
	text-align: center;
	word-spacing: 40px;
	box-shadow: 0px 5px 20px rgba(0,0,0,0.5);
	font-family: 'Ubuntu', sans-serif;
	}
	a:link{
        text-decoration: none;
        color:blue;
	}
	a:visited{
        text-decoration: none;
        color:blue;
	}
	a:hover{
        color:black;
	}
	.l1{
	display: inline;
	}

      </style>
      <body>
<div class="nav">

	   <nav>
        	      <ul>
		      <li class="l1"><a href='{% url "Diseases:Input" %}'>Prognosis</a></li>
		      <li class="l1"><a href='{% url "MainApp:About" %}'>About</a></li>
		      	{% if user.is_authenticated %}
			<li class="l1"><a href = '{% url "Doctor:Adder" %}'>Observation</a></li>
		  	<li class="l1"><a href = '{% url "Doctor:Logout" %}'>Logout</a></li>
			{% else %}
			<li class="l1"><a href = '{% url "Doctor:Login" %}'>Login</a></li>
		      	<li class="l1"><a href = '{% url "Doctor:Registration" %}'>Register</a></li>
			{% endif %}
	              </ul>
	  </nav>
</div>
<br><br><br><br>
      <h1 style="font-size:60px; font-family:'Ubuntu',sans-serif;margin-right:30px;line-height: 0.5;">&nbsp Welcome to</h1>
      <h1 style="font-size:100px; font-family:'Ubuntu',sans-serif;margin-right:30px;line-height:0;">&nbspPrognosist!</h1>
      <h1 style="font-size:50px; font-family:'Ubuntu',sans-serif;"></h1>
      </body>
</html>

DiseasePredictor/media/templates/input.html
<!DOCTYPE html>
<html>
   <head>
      <title>Input page</title>
   <script type ="text/javascript" src="/media/js/jquery.js"></script>
   <script type ="text/javascript" src="/media/js/dropper.js"></script>
      <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
      <style>
          body{
          background-color: #1164b4;
          }
          .div2{
          background-color:white;
          margin: 20px;
          margin-top: 50px ;
          margin-left : 5 px;
          border-radius: 25px;
          padding: 10px;
          text-align: center;
          box-shadow: 0px 5px 20px rgba(0,0,0,0.5);
          font-family: 'Ubuntu', sans-serif;
          position: fixed;
          float :right;
          right:0px;
          width:20%;              }
         .nav{
          background-color:white;
          margin: 20px;
          margin-top: 50px ;
          border-radius: 25px;
          padding: 10px;
          text-align: center;
          box-shadow: 0px 5px 20px rgba(0,0,0,0.5);
          font-family: 'Ubuntu', sans-serif;
              }
          .div1{
          background-color:white;
          margin: 20px;
          margin-right: 5px;
          margin-top: 50px ;
          border-radius: 25px;
          padding: 10px;
          text-align: center;
          box-shadow: 0px 5px 20px rgba(0,0,0,0.5);
          font-family: 'Ubuntu', sans-serif;
          float:left;
          width: 70%;
          position:sticky;
          }
          .textbox{
          border:3px solid red;
          font-size: 20px;
          border-radius: 2px;
          text-align: center;
          }
          .button1{
          border-color: rgb(10, 200, 10);
          color: black;
          font-family: 'Ubuntu', sans-serif;
          border-radius: 20px;
          font-size: 15px;
          padding :5px;
          }
            .symptoms{
               border-radius:25px;
               color:white;
             display:inline-block;
            border:1px solid #CCC;
            box-shadow: 0 0 5px -1px rgba(0,0,0,0.8);
            vertical-align:middle;
            padding: 10px;
            margin: 5px;
            text-align: center;
          }
          .c{
          background-color:green;
          text-color:red;
          }
          .uc{
          background-color:blue;
          text-color:green;
          }
      </style>
   </head>
   <body>
	   {% include "menu-template.html" %}
           <form method="POST" id="target-form" hidden>
         {% csrf_token %}
         {{ form }}
      </form>
      <div class="div1">
      <div class="main-div">
         <h1>Prognosis Analyser</h1>
         <h3 align="left">&nbsp&nbsp Steps to follow:</h3>
         <p align="left">&nbsp&nbsp&nbsp&nbsp 1.Drag and drop symptoms to the box and submit it to run the analysis.</p>
         <p align="left">&nbsp&nbsp&nbsp&nbsp 2.You can submit a maximum of 7 symptoms</p>
         <p align="left">&nbsp&nbsp&nbsp&nbsp 3.To remove a symptom,please drag it back to its original location</p>
         <p align="left">&nbsp&nbsp&nbsp&nbsp 4.In case of any error, try refreshing the page.</p>
         <div class = "section" id = "options" ondragover='allowDrop(event);' ondrop='drop2(event);'>
            <h3 align="left">&nbsp&nbsp Common:</h3> <br>
            <div id="common">
            {% for i in common %}
               <div id='{{ i }}' class = "symptoms noDrop c " draggable='true' ondragstart='drag(event);'>
                  {{ i }}
               </div>
            {% endfor %}
            </div>
            <h3 align="left">&nbsp&nbsp Uncommon:</h3> <br>
            {% for i in uncommon %}
               <div id='{{ i }}' class ="symptoms noDrop uc"  draggable='true' ondragstart='drag(event);'>
                  {{ i }}
               </div>
            {% endfor %}
            <br>
         </div>
         <br>
      </div>
      </div>
      <div class="div2">         
	      <div class = "section"  id = "selections"  ondragover='allowDrop(event);' ondrop='drop1(event);'>
            <h3>Drop your symptoms here</h3>
            <h3>(Maximum {{ length }} symptoms)</h3><br>
         <br>
         <br>
         </div>
         <br>
         <button class="button1" id = "submit">Submit</button>
      </div>
   </body>
</html>

DiseasePredictor/media/templates/login.html
<html><head>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Login page</title>
  <style>
	body{
        background-color: #1164b4;
        }
        body {
        margin:0;
        padding:0;
        background-size: cover;
        background-position-x: center;
        font-family: 'Ubuntu', sans-serif;
        }
        h1,p{
          font-family: 'Ubuntu', sans-serif;
      }        .main {
        background-color: #FFFFFF;
        width: 400px;
        height: 400px;
        margin: 7em auto;
        border-radius: 1.5em;
        box-shadow: 0px 11px 35px 2px rgba(0, 0, 0, 0.14);
        }        .sign {
        padding-top: 40px;
        color: #8C55AA;
        font-family: 'Ubuntu', sans-serif;
        font-weight: bold;
        font-size: 23px;
        }        .un {
        width: 76%;
        color: rgb(38, 50, 56);
        font-weight: 700;
        font-size: 14px;
        letter-spacing: 1px;
        background: rgba(136, 126, 126, 0.04);
        padding: 10px 20px;
        border: none;
        border-radius: 20px;
        outline: none;
        box-sizing: border-box;
        border: 2px solid rgba(0, 0, 0, 0.02);
        margin-bottom: 50px;
        margin-left: 46px;
        text-align: center;
        margin-bottom: 27px;
        font-family: 'Ubuntu', sans-serif;
        }        form.form1 {
        padding-top: 40px;
        }        .pass {
        width: 76%;
        color: rgb(38, 50, 56);
        font-weight: 700;
        font-size: 14px;
        letter-spacing: 1px;
        background: rgba(136, 126, 126, 0.04);
        padding: 10px 20px;
        border: none;
        border-radius: 20px;
        outline: none;
        box-sizing: border-box;
        border: 2px solid rgba(0, 0, 0, 0.02);
        margin-bottom: 50px;
        margin-left: 46px;
        text-align: center;
        margin-bottom: 27px;
        font-family: 'Ubuntu', sans-serif;
        }        .un:focus, .pass:focus {
        border: 2px solid rgba(0, 0, 0, 0.18) !important;        }        .submit {
        cursor: pointer;
        border-radius: 5em;
        color: white;
        background: linear-gradient(to right, #9C27B0, #E040FB);
        border: 0;
        padding-left: 40px;
        padding-right: 40px;
        padding-bottom: 10px;
        padding-top: 10px;
        font-family: 'Ubuntu', sans-serif;
        margin-left: 35%;
        font-size: 13px;
        box-shadow: 0 0 20px 1px rgba(0, 0, 0, 0.04);
        }        
	.forgot {
        text-shadow: 0px 0px 3px rgba(117, 117, 117, 0.12);
        color: #E1BEE7;
        padding-top: 15px;
        }        
	a {
        text-shadow: 0px 0px 3px rgba(117, 117, 117, 0.12);
        color: #E1BEE7;
        text-decoration: none
        }        
	@media (max-width: 600px) {
        .main {
        border-radius: 0px;
        } 
	}
        div#extras {
		align : center;
        width: 76%;
        color: rgb(38, 50, 56);
        font-weight: 700;
        font-size: 14px;
        letter-spacing: 1px;
        background: rgba(255, 0, 0, 0.04);
        padding: 5px 20px;
        border: none;
        border-radius: 20px;
        outline: none;
        box-sizing: border-box;
        border: 2px solid rgba(0, 0, 0, 0.02);
        margin-left: 46px;
        text-align: center;
        font-family: 'Ubuntu', sans-serif;
        } 
  </style>
</head>
<body>
  {% include "menu-template.html" %}	
  <div class="main">
    <p class="sign" align="center">Log in</p>
    <form class="form1" method="POST">
            {% csrf_token %}
         {% if not correct %}
	 <div id="extras">{{ message }}</div><br><br>
         {% endif %}
      <input class="un" type="text" align="center" name="username" placeholder="Username">
      <input class="pass" type="password" name = "password" align="center" placeholder="Password">
      <input class="submit" align="center" type="submit" value="Submit"/>
     <br>
     <br>
    </form>
    </div></body></html>

DiseasePredictor/media/templates/menu-template.html
<style>
.nav{
background-color:white;
margin: 20px;
margin-top: 50px ;
border-radius: 25px;
padding: 10px;
text-align: center;
word-spacing: 40px;
box-shadow: 0px 5px 20px rgba(0,0,0,0.5);
font-family: 'Ubuntu', sans-serif;
}
a:link{
        text-decoration: none;
        color:blue;
}
a:visited{
        text-decoration: none;
        color:blue;
}
a:hover{
        color:black;
}
.l1{
            display: inline;
}
</style>
<div class="nav noDrop">
   <nav>
              <ul>
              <li class="l1"><a href="/">Home</a></li>
	      <li class="l1"><a href='{% url "Diseases:Input" %}'>Prognosis</a></li>
	      <li class="l1"><a href='{% url "MainApp:About" %}'>About</a></li>
	      	{% if user.is_authenticated %}
		<li class="l1"><a href = '{% url "Doctor:Adder" %}'>Observation</a></li>
	  	<li class="l1"><a href = '{% url "Doctor:Logout" %}'>Logout</a></li>
		{% else %}
		<li class="l1"><a href = '{% url "Doctor:Login" %}'>Login</a></li>
	      	<li class="l1"><a href = '{% url "Doctor:Registration" %}'>Register</a></li>
		{% endif %}

              </ul>
  </nav>
</div>

DiseasePredictor/media/templates/message.html
<!DOCTYPE html>
<html>
	<head>
		<title>{{ header }}</title>
	</head>
	<body>
		{% include "menu-template.html" %}
		<h3>{{ message }}!</h3>
	</body>
</html>

DiseasePredictor/media/templates/registration.html
<!DOCTYPE html>
<html>
    <head>
        <title>Input page</title>
      <script type ="text/javascript" src="/media/js/jquery.js"></script>
      <script type ="text/javascript" src="/media/js/dropper.js"></script>
      <style>   
	body{
        background-color: #1164b4;
        }
            .mbody {
            margin:0;
            padding:0;
            background-position-x: left;
            background-position: left;
            font-family: 'Ubuntu', sans-serif;
            }            .main {
            background-color: #ffffffd5;
            width: 400px;
            margin: 7em auto;
            border-radius: 1.5em;
            box-shadow: 0px 11px 35px 2px rgba(138, 255, 102, 0.986);
	    padding : 20px;
            }            .sign {
            padding-top: 40px;
            color: #27aaca;
            font-family: 'Ubuntu', sans-serif;
            font-weight: bold;
            font-size: 23px;
            }            .a {
            width: 76%;
            color: rgb(59, 178, 238);
            font-weight: 700;
            font-size: 14px;
            letter-spacing: 1px;
            background: rgba(255, 255, 255, 0.925);
            padding: 10px 20px;
            border: none;
            border-radius: 20px;
            outline: none;
            box-sizing: border-box;
            border: 2px solid rgb(47, 177, 236);
            margin-bottom: 50px;
            margin-left: 46px;
            text-align: center;
            margin-bottom: 27px;
            font-family: 'Ubuntu', sans-serif;
            }            form.form1 {
            padding-top: 40px;
            }            .b {
            width: 76%;
            color: rgb(59, 178, 238);
            font-weight: 700;
            font-size: 14px;
            letter-spacing: 1px;
            background: rgb(249, 252, 252);
            padding: 10px 20px;
            border: none;
            border-radius: 20px;
            outline: none;
            box-sizing: border-box;
            border: 2px solid rgba(73, 173, 255, 0.986);
            margin-bottom: 50px;
            margin-left: 46px;
            text-align: center;
            margin-bottom: 27px;
            font-family: 'Ubuntu', sans-serif;            }            .c {
            width: 76%;
            color: rgb(59, 178, 238);
            font-weight: 700;
            font-size: 14px;
            letter-spacing: 1px;
            background: rgba(242, 246, 248, 0.993);
            padding: 10px 20px;
            border: none;
            border-radius: 20px;
            outline: none;
            box-sizing: border-box;
            border: 2px solid rgb(77, 169, 255);
            margin-bottom: 50px;
            margin-left: 46px;
            text-align: center;
            margin-bottom: 27px;
            font-family: 'Ubuntu', sans-serif;
            }
            .d{
            width: 76%;
            color: rgb(59, 178, 238);
            font-weight: 700;
            font-size: 14px;
            letter-spacing: 1px;
            background: rgba(255, 255, 255, 0.925);
            padding: 10px 20px;
            border: none;
            border-radius: 20px;
            outline: none;
            box-sizing: border-box;
            border: 2px solid rgba(103, 221, 80, 0.925);
            margin-bottom: 50px;
            margin-left: 46px;
            text-align: center;
            margin-bottom: 27px;
            font-family: 'Ubuntu', sans-serif;
            }
            .e {
            width: 76%;
            color: rgb(59, 178, 238);
            font-weight: 700;
            font-size: 14px;
            letter-spacing: 1px;
            background: rgba(253, 253, 253, 0.925);
            padding: 10px 20px;
            border: none;
            border-radius: 20px;
            outline: none;
            box-sizing: border-box;
            border: 2px solid rgba(150, 243, 89, 0.979);
            margin-bottom: 50px;
            margin-left: 46px;
            text-align: center;
            margin-bottom: 27px;
            font-family: 'Ubuntu', sans-serif;
            }
            .f {
            width: 76%;
            color: rgb(59, 178, 238);
            font-weight: 700;
            font-size: 14px;
            letter-spacing: 1px;
            background: rgba(255, 255, 255, 0.925);
            padding: 10px 20px;
            border: none;
            border-radius: 20px;
            outline: none;
            box-sizing: border-box;
            border: 2px solid rgba(99, 243, 94, 0.966);
            margin-bottom: 50px;
            margin-left: 46px;
            text-align: center;
            margin-bottom: 27px;
            font-family: 'Ubuntu', sans-serif;
            }
            .un:focus, .pass:focus {
            border: 2px solid rgba(0, 0, 0, 0.18) !important;            }
            .submit {
            cursor: pointer;
            border-radius: 5em;
            color: #fff;
            background: linear-gradient(to right, #75e96a, #07da07);
            border: 0;
            padding-left: 40px;
            padding-right: 40px;
            padding-bottom: 10px;
            padding-top: 10px;
            font-family: 'Ubuntu', sans-serif;
            margin-left: 35%;
            font-size: 13px;
            box-shadow: 0 0 20px 1px rgba(0, 0, 0, 0.04);
            }
            a {
            text-shadow: 0px 0px 3px rgba(117, 117, 117, 0.12);
            color: #E1BEE7;
            text-decoration: none
            }            @media (max-width: 600px) {
            .main {
            border-radius: 0px;
            }
      </style>
    </head>    
    <body>
	    {% include "menu-template.html" %}
        <div class="main">
          <p class="sign" align="center">REGISTRATION FORM</p>
          <form class="form1" method="POST">
		  {% csrf_token %}
            <input class="a " name = "username" type="text" align="center" placeholder="USER NAME">
            <input class="b " name = "password" type="password" align="center" placeholder="PASSWORD ">
            <input class="c " name = "email" type="email" align="center" placeholder="ENTER YOUR EMAIL ADDRESS ">
            <input class="d " name = "official_name" type="text" align="center" placeholder="OFFICIAL NAME ">
            <input class="e " name = "mci_id" type="number" align="center" placeholder="MCI ID ">
            <input class="f " name = "registration_year" type="year" align="center" placeholder="REGISTRATION YEAR(YYYY) ">            
	    <input type = "submit" class="submit" align="center" value="SUBMIT"></a>
          </form>
          </div>      
    </body>      
</html>

DiseasePredictor/media/templates/result.html
<!DOCTYPE html>
<html>
   <head>
      <title>Analysis Page</title>
      <style>
          body{
          background-color:  #fcb69f;
          }
         .nav{
          background-color:white;
          margin: 20px;
          margin-top: 50px ;
          border-radius: 25px;
          padding: 10px;
          text-align: center;
          word-spacing: 40px;
          box-shadow: 0px 5px 20px rgba(0,0,0,0.5);
          font-family: 'Ubuntu', sans-serif;
              }
              a:link{
            text-decoration: none;
            color:blue;
            }
            a:visited{
            text-decoration: none;
            color:blue;
            }
            a:hover{
            color:black;
            }
              .l1{
                display: inline;
             }          .div1{
          background-color:white;
          margin: 20px;
          margin-right: 5px;
          margin-top: 50px ;
          border-radius: 25px;
          padding: 10px;
          text-align: center;
          box-shadow: 0px 5px 20px rgba(0,0,0,0.5);
          font-family: 'Ubuntu', sans-serif;
          }
          .div2{
           background-color : rgba(200, 10, 10, 0.2);
           font-family: 'Ubuntu', sans-serif;
           font-size:18px;
          }      </style>
   </head>
   <body>
		{% include "menu-template.html" %}
           <div class="div1">
            <h1>Analysis Result</h1>
            <div align="left">
             <h3><b>&nbsp&nbsp Here is our analysis report:</b></h3>
		{% if multiple %}
		Multiple prognosis detected<br><br>
		<table id="multiResult">
			<thead>
				<td>Prognosis</td>
				<td>Percentage(%)</td>
			</thead>
			<tbody>
				{% for i,j in prognosis %}
				<tr>
					<td>{{ i }}</td>
					<td>{{ j }}</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
		<br>
		**rest of the results ommited due to low probability
		{% else %}
                <ul>
			<li style="font-size:20px">{{ prognosis }}</li>
                </ul>
		{% endif %}
                <div class="div2">
                    <p><b> &nbsp&nbsp Note:&nbsp This is a completely computer generated prognosis report! Please do not consider this as a final report.Consult a doctor before taking medicine.</b></p>                </div>
            </div>        </div>
   </body>
</html>

DiseasePredictor/media/templates/something_wrong.html
<!DOCTYPE html>
<html>
   <head>
	   <title>{{ title }}</title>
      <style>
            body{
		    background-color: #1164b4;
            }
          .div1{
          background-color:white;
          margin: 20px;
          margin-right: 5px;
          margin-top: 50px ;
          border-radius: 25px;
          padding: 10px;
          text-align: center;
          box-shadow: 0px 5px 20px rgba(0,0,0,0.5);
          font-family: 'Ubuntu', sans-serif;
          }      </style>
   </head>
   <body>
	   {% include "menu-template.html" %}
      <div class="div1">
	      <h1>{{ heading }}</h1>
	      <p>{{ message }}</p>
        </div>
   </body>
</html>